### ISSUE TITLE
What are the benefits of keeping an eye on the versions?

### ISSUE THREAD

**Issue by petrokoriakin1** [bobf/strong_versions#5]
strong_versions hasn't got any update since 4 years ago, is it still maintained?

How would enforcing us to use specific version benefit us?

**Comment by petrokoriakin1** [comment]
@bobf , we are [FotoFinder Systems GmbH](https://github.com/FotoFinderSystems) and we want to use `[strong_versions](https://github.com/bobf/strong_versions)` 

Does it sounds reasonable from your perspective and MIT license perspective?

**Comment by bobf** [comment]
Hi, @petrokoriakin1 - StrongVersions does not enforce specific versions, only the format of version constraints to try to help prevent upgrading to incompatible versions, as well as preventing unnecessarily precise constraints which can result in gems being stuck on old versions when they could be safely upgraded. 

This gem has not been updated in a long time but it is maintained - if a bug is reported or if a good feature is suggested I will fix/implement it, but the gem is "complete" for what it was intended to do. 

The MIT license permits you to use this gem and its code in any context, you just have to include the license if you distribute the code, otherwise it is free for everyone for any purpose.

Thanks for your interest in the gem.

**Comment by petrokoriakin1** [comment]
thanks for the clarity!
